-- cf-visitas – initial schema
-- Apply locally:  npm run db:migrate
-- Apply remotely: npm run db:migrate:remote

CREATE TABLE IF NOT EXISTS visits (
  id                   INTEGER PRIMARY KEY AUTOINCREMENT,
  ts                   TEXT    NOT NULL,
  fingerprint          TEXT    NOT NULL,
  ip                   TEXT    NOT NULL DEFAULT '',
  url                  TEXT    NOT NULL DEFAULT '',
  referrer             TEXT    NOT NULL DEFAULT '',
  browser              TEXT    NOT NULL DEFAULT '',
  browser_version      TEXT    NOT NULL DEFAULT '',
  os                   TEXT    NOT NULL DEFAULT '',
  os_version           TEXT    NOT NULL DEFAULT '',
  device               TEXT    NOT NULL DEFAULT '',
  device_type          TEXT    NOT NULL DEFAULT '',
  device_vendor        TEXT    NOT NULL DEFAULT '',
  engine               TEXT    NOT NULL DEFAULT '',
  engine_version       TEXT    NOT NULL DEFAULT '',
  language             TEXT    NOT NULL DEFAULT '',
  timezone             TEXT    NOT NULL DEFAULT '',
  resolution           TEXT    NOT NULL DEFAULT '',
  color_depth          INTEGER,
  hardware_concurrency INTEGER,
  device_memory        REAL,
  country              TEXT,
  region               TEXT,
  city                 TEXT,
  org                  TEXT,
  latitude             REAL,
  longitude            REAL,
  properties           TEXT    NOT NULL DEFAULT '{}',
  hardware             TEXT    NOT NULL DEFAULT '{}',
  sensors              TEXT    NOT NULL DEFAULT '{}',
  meta                 TEXT    NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_visits_ts          ON visits (ts);
CREATE INDEX IF NOT EXISTS idx_visits_fingerprint ON visits (fingerprint);
CREATE INDEX IF NOT EXISTS idx_visits_country     ON visits (country);
CREATE INDEX IF NOT EXISTS idx_visits_browser     ON visits (browser);

CREATE TABLE IF NOT EXISTS blocked_fingerprints (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  fingerprint TEXT    NOT NULL UNIQUE,
  reason      TEXT    NOT NULL DEFAULT '',
  created_at  TEXT    NOT NULL,
  hits        INTEGER NOT NULL DEFAULT 0,
  last_hit_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_blocked_fingerprint ON blocked_fingerprints (fingerprint);

-- Asymmetric key pairs used by the tracker. Generated by the Worker itself,
-- stored here and rotated periodically (see lib/keys.ts).
CREATE TABLE IF NOT EXISTS tracker_keys (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  public_key  TEXT    NOT NULL,
  private_key TEXT    NOT NULL,
  created_at  TEXT    NOT NULL,
  expires_at  TEXT    NOT NULL,
  retired_at  TEXT,
  active      INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_tracker_keys_active ON tracker_keys (active);
