/**
 * Tracker key store.
 *
 * Visit payloads are encrypted with hybrid post-quantum cryptography:
 * ML-KEM-1024 (FIPS 203) encapsulates a shared secret that HKDF-SHA256 turns
 * into an AES-256-GCM key. The ML-KEM key pair is generated by the Worker
 * itself, persisted in D1 and rotated periodically:
 *
 *   - The active key is used for new `/tracker.js` responses and expires after
 *     `TRACKER_KEY_ROTATION_DAYS` (default 30 days).
 *   - When it expires, when an admin rotates it manually, or when the key
 *     algorithm changes (e.g. legacy RSA-OAEP → ML-KEM), the old key is marked
 *     as retired but kept for a grace period so trackers served before the
 *     switch can still be decrypted.
 *   - Retired keys are deleted once the grace period is over.
 *
 * Nothing here needs to be configured by hand: the first tracker request (or
 * the first visit to /keys) creates the initial key pair.
 */

import { env } from "cloudflare:workers";
import { generatePqKeyPair, PQ_ALGORITHM } from "./pq";
import type { TrackerKeyInfo } from "./types";

export const KEY_ROTATION_DAYS_DEFAULT = 30;
export const KEY_GRACE_DAYS = 3;

/** Algorithm used for new key pairs. Legacy keys are still decryptable. */
export const CURRENT_ALGORITHM = PQ_ALGORITHM;

const ACTIVE_KEY_CACHE_TTL_MS = 60_000;

export interface TrackerKey {
  id: number;
  algorithm: string;
  publicKey: string;
  privateKey: string;
  createdAt: string;
  expiresAt: string;
  active: boolean;
  retiredAt: string | null;
}

let activeKeyCache: { at: number; key: TrackerKey | null } | null = null;
const keyMaterialCache = new Map<number, TrackerKey>();

export function getRotationDays(): number {
  const parsed = Number.parseInt(env.TRACKER_KEY_ROTATION_DAYS ?? "", 10);
  if (!Number.isFinite(parsed) || parsed < 1 || parsed > 365) return KEY_ROTATION_DAYS_DEFAULT;
  return parsed;
}

export function invalidateTrackerKeyCache(): void {
  activeKeyCache = null;
}

function rowToKey(row: Record<string, unknown>): TrackerKey {
  return {
    id: Number(row.id),
    algorithm: String(row.algorithm ?? ""),
    publicKey: String(row.public_key),
    privateKey: String(row.private_key),
    createdAt: String(row.created_at),
    expiresAt: String(row.expires_at),
    active: Number(row.active) === 1,
    retiredAt: row.retired_at === null || row.retired_at === undefined ? null : String(row.retired_at),
  };
}

async function readActiveKeyRow(): Promise<Record<string, unknown> | null> {
  return env.DB.prepare("SELECT * FROM tracker_keys WHERE active = 1 ORDER BY id DESC LIMIT 1").first<
    Record<string, unknown>
  >();
}

/**
 * Returns the active key, or `null` when there is none, it has expired or it
 * uses a different algorithm than the current one.
 */
export async function getActiveTrackerKey(): Promise<TrackerKey | null> {
  const now = Date.now();
  if (activeKeyCache && now - activeKeyCache.at < ACTIVE_KEY_CACHE_TTL_MS) return activeKeyCache.key;

  const row = await readActiveKeyRow();
  let key = row ? rowToKey(row) : null;
  if (key && (Date.parse(key.expiresAt) <= now || key.algorithm !== CURRENT_ALGORITHM)) key = null;
  activeKeyCache = { at: now, key };
  return key;
}

/** Returns the active key, generating one when needed. */
export async function ensureActiveTrackerKey(): Promise<TrackerKey> {
  const existing = await getActiveTrackerKey();
  if (existing) return existing;
  return rotateTrackerKey({ force: false });
}

/**
 * Generates a new ML-KEM key pair and makes it the active one.
 *
 * `force: false` only retires keys that have expired or use another algorithm,
 * so concurrent isolates converge on a single active key (the conditional
 * insert makes the race safe). `force: true` retires the current key
 * immediately (manual rotation).
 */
export async function rotateTrackerKey({ force }: { force: boolean }): Promise<TrackerKey> {
  const now = new Date();
  const rotationDays = getRotationDays();
  const createdAt = now.toISOString();
  const expiresAt = new Date(now.getTime() + rotationDays * 86_400_000).toISOString();
  const graceCutoff = new Date(now.getTime() - KEY_GRACE_DAYS * 86_400_000).toISOString();

  const keyPair = generatePqKeyPair();

  const retireStatement = force
    ? env.DB.prepare("UPDATE tracker_keys SET active = 0, retired_at = ?1 WHERE active = 1").bind(createdAt)
    : env.DB.prepare(
        "UPDATE tracker_keys SET active = 0, retired_at = ?1 WHERE active = 1 AND (expires_at <= ?1 OR algorithm != ?2)",
      ).bind(createdAt, CURRENT_ALGORITHM);

  await env.DB.batch([
    retireStatement,
    env.DB.prepare(
      `INSERT INTO tracker_keys (public_key, private_key, algorithm, created_at, expires_at, active)
       SELECT ?1, ?2, ?3, ?4, ?5, 1
       WHERE NOT EXISTS (SELECT 1 FROM tracker_keys WHERE active = 1)`,
    ).bind(keyPair.publicKey, keyPair.privateKey, CURRENT_ALGORITHM, createdAt, expiresAt),
    env.DB.prepare(
      "DELETE FROM tracker_keys WHERE active = 0 AND retired_at IS NOT NULL AND retired_at < ?1",
    ).bind(graceCutoff),
  ]);

  const row = await readActiveKeyRow();
  if (!row) throw new Error("Unable to create a tracker key");

  const key = rowToKey(row);
  activeKeyCache = { at: Date.now(), key };
  keyMaterialCache.clear();
  return key;
}

/** Key metadata for the admin UI (never exposes key material). */
export async function listTrackerKeys(limit = 20): Promise<TrackerKeyInfo[]> {
  const result = await env.DB.prepare(
    `SELECT id, algorithm, created_at, expires_at, retired_at, active
     FROM tracker_keys
     ORDER BY id DESC
     LIMIT ?1`,
  )
    .bind(Math.min(Math.max(limit, 1), 100))
    .all<Record<string, unknown>>();

  return (result.results ?? []).map((row) => ({
    id: Number(row.id),
    algorithm: String(row.algorithm ?? ""),
    createdAt: String(row.created_at),
    expiresAt: String(row.expires_at),
    retiredAt: row.retired_at === null || row.retired_at === undefined ? null : String(row.retired_at),
    active: Number(row.active) === 1,
  }));
}

/** Returns the key material for a key id (active or within the grace period). */
export async function getKeyMaterialForKid(kid: number): Promise<TrackerKey | null> {
  const cached = keyMaterialCache.get(kid);
  if (cached) return cached;

  const row = await env.DB.prepare("SELECT * FROM tracker_keys WHERE id = ?1").bind(kid).first<Record<string, unknown>>();
  if (!row) return null;

  const key = rowToKey(row);
  keyMaterialCache.set(kid, key);
  return key;
}
