/**
 * Tracker key store.
 *
 * The RSA-2048 key pair used to encrypt visit payloads is generated by the
 * Worker itself (WebCrypto), persisted in D1 and rotated periodically:
 *
 *   - The active key is used for new `/tracker.js` responses and expires after
 *     `TRACKER_KEY_ROTATION_DAYS` (default 30 days).
 *   - When it expires (or when an admin rotates it manually) the old key is
 *     marked as retired but kept for a grace period so in-flight trackers can
 *     still be decrypted.
 *   - Retired keys are deleted once the grace period is over.
 *
 * Nothing here needs to be configured by hand: the first tracker request (or
 * the first visit to /keys) creates the initial key pair.
 */

import { env } from "cloudflare:workers";
import type { TrackerKeyInfo } from "./types";

export const KEY_ROTATION_DAYS_DEFAULT = 30;
export const KEY_GRACE_DAYS = 3;

const ACTIVE_KEY_CACHE_TTL_MS = 60_000;

export interface TrackerKey {
  id: number;
  publicJwk: JsonWebKey;
  privateJwk: JsonWebKey;
  createdAt: string;
  expiresAt: string;
  active: boolean;
  retiredAt: string | null;
}

let activeKeyCache: { at: number; key: TrackerKey | null } | null = null;
const privateKeyCache = new Map<number, Promise<CryptoKey>>();

export function getRotationDays(): number {
  const parsed = Number.parseInt(env.TRACKER_KEY_ROTATION_DAYS ?? "", 10);
  if (!Number.isFinite(parsed) || parsed < 1 || parsed > 365) return KEY_ROTATION_DAYS_DEFAULT;
  return parsed;
}

export function invalidateTrackerKeyCache(): void {
  activeKeyCache = null;
}

function rowToKey(row: Record<string, unknown>): TrackerKey {
  return {
    id: Number(row.id),
    publicJwk: JSON.parse(String(row.public_key)) as JsonWebKey,
    privateJwk: JSON.parse(String(row.private_key)) as JsonWebKey,
    createdAt: String(row.created_at),
    expiresAt: String(row.expires_at),
    active: Number(row.active) === 1,
    retiredAt: row.retired_at === null || row.retired_at === undefined ? null : String(row.retired_at),
  };
}

async function readActiveKeyRow(): Promise<Record<string, unknown> | null> {
  return env.DB.prepare("SELECT * FROM tracker_keys WHERE active = 1 ORDER BY id DESC LIMIT 1").first<
    Record<string, unknown>
  >();
}

/** Returns the active key, or `null` when there is none (or it has expired). */
export async function getActiveTrackerKey(): Promise<TrackerKey | null> {
  const now = Date.now();
  if (activeKeyCache && now - activeKeyCache.at < ACTIVE_KEY_CACHE_TTL_MS) return activeKeyCache.key;

  const row = await readActiveKeyRow();
  let key = row ? rowToKey(row) : null;
  if (key && Date.parse(key.expiresAt) <= now) key = null;
  activeKeyCache = { at: now, key };
  return key;
}

/** Returns the active key, generating one when needed. */
export async function ensureActiveTrackerKey(): Promise<TrackerKey> {
  const existing = await getActiveTrackerKey();
  if (existing) return existing;
  return rotateTrackerKey({ force: false });
}

/**
 * Generates a new key pair and makes it the active one.
 *
 * `force: false` only retires keys that have expired, so concurrent isolates
 * converge on a single active key (the conditional insert makes the race safe).
 * `force: true` retires the current key immediately (manual rotation).
 */
export async function rotateTrackerKey({ force }: { force: boolean }): Promise<TrackerKey> {
  const now = new Date();
  const rotationDays = getRotationDays();
  const createdAt = now.toISOString();
  const expiresAt = new Date(now.getTime() + rotationDays * 86_400_000).toISOString();
  const graceCutoff = new Date(now.getTime() - KEY_GRACE_DAYS * 86_400_000).toISOString();

  const keyPair = await crypto.subtle.generateKey(
    {
      name: "RSA-OAEP",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["encrypt", "decrypt"],
  );
  const publicJwk = await crypto.subtle.exportKey("jwk", keyPair.publicKey);
  const privateJwk = await crypto.subtle.exportKey("jwk", keyPair.privateKey);

  const retireStatement = force
    ? env.DB.prepare("UPDATE tracker_keys SET active = 0, retired_at = ?1 WHERE active = 1").bind(createdAt)
    : env.DB.prepare("UPDATE tracker_keys SET active = 0, retired_at = ?1 WHERE active = 1 AND expires_at <= ?1").bind(
        createdAt,
      );

  await env.DB.batch([
    retireStatement,
    env.DB.prepare(
      `INSERT INTO tracker_keys (public_key, private_key, created_at, expires_at, active)
       SELECT ?1, ?2, ?3, ?4, 1
       WHERE NOT EXISTS (SELECT 1 FROM tracker_keys WHERE active = 1)`,
    ).bind(JSON.stringify(publicJwk), JSON.stringify(privateJwk), createdAt, expiresAt),
    env.DB.prepare(
      "DELETE FROM tracker_keys WHERE active = 0 AND retired_at IS NOT NULL AND retired_at < ?1",
    ).bind(graceCutoff),
  ]);

  const row = await readActiveKeyRow();
  if (!row) throw new Error("Unable to create a tracker key");

  const key = rowToKey(row);
  activeKeyCache = { at: Date.now(), key };
  return key;
}

/** Key metadata for the admin UI (never exposes key material). */
export async function listTrackerKeys(limit = 20): Promise<TrackerKeyInfo[]> {
  const result = await env.DB.prepare(
    `SELECT id, created_at, expires_at, retired_at, active
     FROM tracker_keys
     ORDER BY id DESC
     LIMIT ?1`,
  )
    .bind(Math.min(Math.max(limit, 1), 100))
    .all<Record<string, unknown>>();

  return (result.results ?? []).map((row) => ({
    id: Number(row.id),
    createdAt: String(row.created_at),
    expiresAt: String(row.expires_at),
    retiredAt: row.retired_at === null || row.retired_at === undefined ? null : String(row.retired_at),
    active: Number(row.active) === 1,
  }));
}

/** Imports the private key for a key id (active or within the grace period). */
export async function getPrivateKeyForKid(kid: number): Promise<CryptoKey | null> {
  const cached = privateKeyCache.get(kid);
  if (cached) return cached.catch(() => null);

  const promise = (async () => {
    const row = await env.DB.prepare("SELECT private_key FROM tracker_keys WHERE id = ?1")
      .bind(kid)
      .first<{ private_key: string }>();
    if (!row) throw new Error(`Tracker key ${kid} not found`);
    const jwk = JSON.parse(row.private_key) as JsonWebKey;
    return crypto.subtle.importKey("jwk", jwk, { name: "RSA-OAEP", hash: "SHA-256" }, false, ["decrypt"]);
  })();

  privateKeyCache.set(kid, promise);
  promise.catch(() => privateKeyCache.delete(kid));
  return promise.catch(() => null);
}
