/**
 * Builds the `/tracker.js` response: the obfuscated tracker bundle plus a
 * per-request config (endpoint, active public key, signed blocklist metadata).
 *
 * The bundle is produced by `scripts/build-tracker.mjs` and is not readable:
 * no comments, encoded strings, renamed identifiers and flattened control flow.
 * The config is injected as `window.__vx` (base64-encoded) before the bundle.
 *
 * The encryption key pair is generated by the Worker and stored in D1 — see
 * `lib/keys.ts` for the rotation policy.
 */

import { env } from "cloudflare:workers";
import trackerBundle from "@/tracker/tracker.dist.js?raw";
import { getBlockedHashes } from "./db";
import { ensureActiveTrackerKey } from "./keys";
import { signTrackerConfig, TRACKER_VERSION } from "./signature";

/** base64 of "__vx" — the global the bundle reads the config from. */
const CONFIG_PROPERTY_BASE64 = "X192eA==";

export interface TrackerConfig {
  version: number;
  kid: number;
  algorithm: string;
  endpoint: string;
  publicKey: string;
  blocked: string[];
  issuedAt: number;
  expiresAt: number;
  blocklistHash: string;
  signature: string;
}

export async function buildTrackerConfig(origin: string): Promise<TrackerConfig> {
  const [blocked, key] = await Promise.all([getBlockedHashes(), ensureActiveTrackerKey()]);
  const signature = await signTrackerConfig(key.id, blocked);

  // `TRACKER_ENDPOINT_ORIGIN` lets local development point the tracker at the
  // dev server (Wrangler rewrites the request host to the custom-domain route).
  const endpointOrigin = (env.TRACKER_ENDPOINT_ORIGIN ?? "").trim().replace(/\/+$/, "") || origin;

  return {
    version: TRACKER_VERSION,
    kid: key.id,
    algorithm: key.algorithm,
    endpoint: `${endpointOrigin}/api/track`,
    publicKey: key.publicKey,
    blocked,
    ...signature,
  };
}

function toBase64(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export async function buildTrackerScript(origin: string): Promise<string> {
  const config = await buildTrackerConfig(origin);
  const encodedConfig = toBase64(JSON.stringify(config));
  const bootstrap = `(function(){var d=function(s){return atob(s)};window[d("${CONFIG_PROPERTY_BASE64}")]=JSON.parse(d("${encodedConfig}"));})();`;
  return `${bootstrap}${trackerBundle}`;
}
